### ISSUE TITLE
Ask a question

### ISSUE THREAD

**Issue by zxfzqf** [breadbread1984/deepid#1]
您好，不介意我用中文吧。
看了您 关于 数据预处理的代码deepid/src/generate_training_samples.cpp ，对我帮助很大。
感谢！
但是我还有个疑问关于generate_training_samples.cpp：
`//三种尺度，patch的高，patch的宽，两眼距离占宽的比例
static const boost::tuple<float,float> scales[] = {boost::make_tuple(0.4f,0.64f),boost::make_tuple(0.3f,0.48f),boost::make_tuple(0.24f,0.39f)};`
这行代码种，关于这个两眼距离占宽的比例的具体的数值您是怎么得到的呢？我在论文里没有看到相关信息。

**Comment by breadbread1984** [comment]
论文上面确实没有，我自己尝试的比例。你也可以尝试其他的比例看看是不是有助于提取出更好的deepid特征。
